version: 2

mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
  - when: pull_request.*
    validate:
      - do: dependent
        changed:
          file: 'package.json' # also supports globs expressions
          required: ['package-lock.json', 'yarn.lock'] # alias: `files` for backward compatibility
  # - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
  #   name: 'Automatically merge pull requests once it passes all checks'
  #   validate: []
  #   pass:
  #     - do: merge
  #       merge_method: 'squash'
