name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

      # Due to Github Actions design, releases created by this action won't trigger
      # new Actions like `npm-publish.ym`, so we have to handle the npm publication here.
      # More info:
      # https://github.com/google-github-actions/release-please-action/issues/402
      # https://github.com/googleapis/release-please/issues/1142
      - uses: actions/checkout@v4
        # These if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --immutable

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
